View:
  onLoad:
    invokeApi:
      name: getData
      onResponse:
        executeCode: |
          ensemble.storage.set("arrayOfUsers",response.body.records)
          const groups = new Set(response.body.records.flatMap(record => record.fields.groups))
          ensemble.storage.set("arrayOfGroups", Array.from(groups))
  body:
    Column:
      crossAxis: stretch
      margin: 0 20px
      gap: 10
      children:
        - Row:
            backgroundColor: white
            mainAxis: spaceBetween
            crossAxis: center
            padding: 10
            styles:
              borderBottom: "1px #D5DAEA solid"
            children:
              - Search:
                  styles:
                    width: 320px
                    height: 40px
                    borderRadius: 12
                    borderWidth: 2
                    borderStyle: solid
                    borderColor: "#B8BED6"
                  placeholder: Search
                  data: getData.body.users
                  searchKey: email
              - Row:
                  styles:
                    gap: 10
                  children:
                    - Avatar:
                        styles:
                          backgroundColor: "#171B2A"
                        alt: abc
                        name: Adam
                        menu:
                          - label: Personal Information
                            icon: Person
                            onTap:
                              executeCode: myText.setText("Spiderman")
                          - label: Collections
                            icon: Settings
                            onTap:
                              navigateScreen: Collections
        - Row:
            mainAxis: spaceBetween
            crossAxis: center
            children:
              - Markdown:
                  text: "# Product and Development"
        

        - Conditional:
            conditions:
              - if: ${!getData.body.records}
                Row:
                  crossAxis: center
                  gap: 24
                  children:
                    - Card:
                        styles:
                          shadowColor: lightgrey
                          shadowOffset: 8px
                          shadowBlur: 10px
                          shadowSpread: -2px
                          backgroundColor: white
                        children:
                          - Column:
                              crossAxis: start
                              gap: 24
                              children:
                                - Text:
                                    text: 📂
                                    styles:
                                      fontSize: 32
                                - Column:
                                    styles:
                                      crossAxis: center
                                    children:
                                      - Text:
                                          text: Add your first collection
                                          styles:
                                            fontSize: 26
                                            fontWeight: 600
                                            color: "#28304B"
                                            fontFamily: Inter
                                      - Text:
                                          text: Create a new collection to start adding content to your knowledge base.
                                          styles:
                                            fontSize: 15
                                            fontWeight: 400
                                            color: "#565D80"
                                            fontFamily: Inter
                                - Button:
                                    label: Create collection
                                    startingIcon:
                                      name: Add
                                      color: white
                                      size: 22
                                    onTap:
                                      navigateModalScreen:
                                        name: Create Group
                                        maskClosable: false

              - else:
                Column:
                  children:
                    - Column:
                        styles:
                          borderWidth: 1px
                          borderRadius: 10
                          borderColor: "#e8e9eb"
                          backgrounColor: white
                        children:
                          - Row:
                              mainAxis: spaceBetween
                              crossAxis: center
                              padding: "10px 20px 0px 20px"
                              children:
                                - Markdown:
                                    text: '### Access to Collection'
                                - Button:
                                    label: Create collection
                                    styles:
                                      textColor: black
                                      backgroundColor: white
                                      padding: 16
                                    gap: 6
                                    startingIcon:
                                      name: Add
                                      color: black
                                      size: 22
                                    onTap:
                                      navigateModalScreen:
                                        name: group
                                        maskClosable: false
                          - Column:
                              styles:
                                borderWidth: 1px
                                borderRadius: 10
                                borderColor: "#e8e9eb"
                                backgrounColor: white
                                padding: 20
                                margin: 20
                              children:  
                                - GridView:
                                    styles:
                                      horizontalTileCount: 3
                                      horizontalGap: 5
                                    item-template:
                                      data: getData.body.records
                                      name: user
                                      template:
                                        Card:
                                          styles:
                                            shadowColor: lightgrey
                                            shadowOffset: 8px
                                            shadowBlur: 10px
                                            shadowSpread: -2px
                                            backgroundColor: white
                                            minWidth: 300px
                                            maxWidth: 300px
                                          children:
                                            - Column:
                                                gap: 10
                                                children:
                                                  - Row:
                                                      mainAxis: spaceBetween
                                                      gap: 20
                                                      children:
                                                        
                                                        - Avatar:
                                                            styles:
                                                              backgroundColor: "#D9D9D9"
                                                            alt: abc
                                                            name: ${user.fields.Name}
                                                        - Column:
                                                            styles:
                                                              crossAxis: center
                                                              gap: 5
                                                            children:
                                                              - Column:
                                                                  styles:
                                                                    crossAxis: start
                                                                  children:
                                                                    - Text:
                                                                        text: ${user.fields.Name}
                                                                        styles: 
                                                                          fontSize: 16
                                                                          fontWeight: 700
                                                                    - Text:
                                                                        text: ${user.fields.users}
                                                        - PopupMenu:
                                                            items:
                                                              - { "label": "View", "value": "red" }
                                                              - { "label": "Remove", "value": "blue" }
                                                              - { "label": "Edit", "value": "green" }
                                                            onItemSelect:
                                                              navigateModalScreen:
                                                                name: Ask Embrace
                                                            widget:
                                                              Icon:
                                                                name: MoreVert
                    - Column:
                        styles:
                          borderWidth: 1px
                          borderRadius: 10
                          borderColor: "#e8e9eb"
                          backgrounColor: white
                          padding: 20
                          margin: "20px 0px 20px 0px"
                          gap: 20
                        children:
                          - Row:
                              children:
                                - Markdown:
                                    text: "## Sources in collections"
                          - Column:
                              mainAxis: center
                              crossAxis: center
                              gap: 10
                              children:
                                - Icon:
                                    name: LibraryBooksOutlined
                                    size: 50
                                    color: black
                                - Text:
                                    text: Add content sources
                                    styles:
                                      fontSize: 20
                                      fontWeight: 700
                                - Text:
                                    text: Start adding sources to this collection
                                - Button:
                                    label: Add content source
                                    styles:
                                      textColor: blue
                                      backgroundColor: white
                                      borderColor: blue
                                      padding: 10
                                    onTap:
                                      navigateModalScreen:
                                        name: group
                                        maskClosable: false
                                
                                            
                                            
        


API:
  getData:
    uri: https://api.airtable.com/v0/appachBOsD5ZSdH8t/tbl3vjz4Zs29PGQjB
    method: GET
    headers:
      Authorization: Bearer patN2XAiLVZQ8Yp3h.2bddb84031b2be89b576f01869dc17c3826e16ae7daa8895f92c05a0799004ab
