/**
 * DTOs = Data Transfer Objects
 *
 * Mostly equivalent to raw JSON definition over wire
 */
export interface EnsembleDocument {
  readonly id: string;
  readonly name: string;
  readonly content: string;
  readonly type: EnsembleDocumentType;

  readonly description?: string;
  readonly isRoot?: boolean;
  readonly isDraft?: boolean;
  readonly isArchived?: boolean;
  readonly updatedAt?: Date;
  readonly updatedBy?: {
    name: string;
  };
}

export enum EnsembleDocumentType {
  I18n = "i18n",
  Theme = "theme",
  Asset = "asset",
  Screen = "screen",
  Font = "font",
  Widget = "internal_widget",
  Script = "internal_script",
  Environment = "appConfig",
  Secrets = "secrets",
}

export interface ApplicationDTO
  extends Omit<EnsembleDocument, "content" | "type"> {
  readonly description?: string;
  readonly isPublic?: boolean;
  readonly isAutoGenerated?: boolean;
  readonly isReact?: boolean;
  readonly status?: string;
  readonly category?: AppCategory;
  readonly collaborators?: Map<string, AccessType>;
  readonly demoOrder?: number;
  readonly publishingHistory?: PublishingHistory[];
  readonly groupLabels?: Map<string, string>;

  readonly manifest?: Record<
    string,
    Partial<EnsembleDocument> & {
      filePath?: string;
    }
  >;

  readonly screens: ScreenDTO[];
  readonly widgets: WidgetDTO[];
  readonly scripts: ScriptDTO[];
  readonly theme?: ThemeDTO;
  readonly themes?: ThemeDTO[];
  readonly languages?: LanguageDTO[];
  readonly config?: string | EnsembleConfigYAML;
  readonly fonts?: FontDTO[];
}

export interface HasLabel {
  labelGroup?: string;
}

export interface PublishingHistory {
  publishedTo: string;
  createdAt: Date;
  publishedBy: string;
  publishingLog: string;
  role: string;
}

export type EnsembleLabeledDocument = EnsembleDocument & HasLabel;

export type ScreenDTO = EnsembleLabeledDocument & {
  type: EnsembleDocumentType.Screen;

  readonly path?: string;
  // deprecated?
  readonly category?: string;
};

export type WidgetDTO = EnsembleLabeledDocument & {
  type: EnsembleDocumentType.Widget;
};

export type ScriptDTO = EnsembleLabeledDocument & {
  type: EnsembleDocumentType.Script;
};
export type ThemeDTO = EnsembleDocument & {
  type: EnsembleDocumentType.Theme;
};

export interface LanguageDTO {
  readonly name: string;
  readonly nativeName: string;
  readonly languageCode: string;
  readonly content: string;
}

export interface EnsembleEnvironmentDTO {
  googleOAuthId?: string;
}

export interface EnsembleConfigYAML {
  environmentVariables?: Record<string, unknown>;
  secretVariables?: Record<string, unknown>;
}

export type FontDTO = EnsembleDocument & {
  readonly fontFamily: string;
  readonly fontWeight: string;
  readonly fontStyle: string;
  readonly fontType: string;
  readonly publicUrl?: string;
};

export enum AppCategory {
  Demo = "Demo",
  Template = "Template",
}

export enum AccessType {
  Read = "read",
  Write = "write",
  Owner = "owner",
}

export type EnsembleDocumentHistoryItem = EnsembleDocument & {
  readonly comment: string;
  readonly label: string;
};
